name: Sync Upstream
on:
  schedule:
    - cron: '0 * * * *'  # 每小时检查一次（可调整）
  workflow_dispatch:     # 支持手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync Fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "RockChinQ/LangBot"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
